version: "3.7"

services:

  #databases
  login-db:
    container_name: login-db
    image: postgres:14-alpine
    expose:
      - "5432"
    volumes:
      - ./data/login-db:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=super_secure_password

  # database setup
  login-db-setup:
    image: ghcr.io/gamify-it/login-backend:latest
    restart: on-failure
    depends_on:
      - login-db
    working_dir: /app
    volumes:
      - .:/app:ro
    command: go run github.com/prisma/prisma-client-go migrate deploy
    environment:
      POSTGRES_URL: postgresql://postgres:super_secure_password@login-db:5432/postgres

  #frontends
  login-frontend:
    container_name: login-frontend
    image: ghcr.io/gamify-it/login-frontend:latest
    restart: always
    expose:
      - "80"

  # reverse-proxy
  reverse-proxy:
    container_name: reverse-proxy
    image: nginx
    restart: always
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
