// Package main runs the HTTP server.
package main

//go:generate go run github.com/prisma/prisma-client-go generate
//go:generate go run github.com/go-swagger/go-swagger/cmd/swagger generate server --target ./src/gen --name Login --spec ./swagger/swagger.yml --principal interface{} --exclude-main

import (
	_ "github.com/go-swagger/go-swagger"

	"github.com/Gamify-IT/login-backend/src/gen/restapi"
	"github.com/Gamify-IT/login-backend/src/gen/restapi/operations"
	"log"
	"os"

	"github.com/go-openapi/loads"
	flags "github.com/jessevdk/go-flags"
)

// The main function was generated by go-swagger.
func main() {

	swaggerSpec, err := loads.Embedded(restapi.SwaggerJSON, restapi.FlatSwaggerJSON)
	if err != nil {
		log.Fatalln(err)
	}

	api := operations.NewLoginAPI(swaggerSpec)
	server := restapi.NewServer(api)
	defer server.Shutdown()

	parser := flags.NewParser(server, flags.Default)
	parser.ShortDescription = "Login API"
	parser.LongDescription = "API for user authentication"
	server.ConfigureFlags()
	for _, optsGroup := range api.CommandLineOptionsGroups {
		_, err := parser.AddGroup(optsGroup.ShortDescription, optsGroup.LongDescription, optsGroup.Options)
		if err != nil {
			log.Fatalln(err)
		}
	}

	if _, err := parser.Parse(); err != nil {
		code := 1
		if fe, ok := err.(*flags.Error); ok {
			if fe.Type == flags.ErrHelp {
				code = 0
			}
		}
		os.Exit(code)
	}

	server.ConfigureAPI()

	if err := server.Serve(); err != nil {
		log.Fatalln(err)
	}
}
