name: Tests
on: [push]
jobs:
  unit-test:
    name: "Unit tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.18

      - uses: actions/checkout@master

      - run: go mod download

      - run: go generate

      - run: go test -v ./...
